### ISSUE TITLE
Too many sync messages, is there a way to block them?

### ISSUE THREAD

**Issue by Donzelinho** [remotely-save/donation#1]
Hi, 
  This plugin is very useful, but too many sync messages keep popping up, it's quite annoying. Is there a way to block them?

**Comment by exoticknight** [comment]
> Hi, 
> 
>   This plugin is very useful, but too many sync messages keep popping up, it's quite annoying. Is there a way to block them? 

Thanks for reaching out. It looks like this issue has been posted in the wrong repository. For better assistance and to ensure your issue is addressed by the right team, could you please repost it in the correct repository? You can find the appropriate repository link here: https://github.com/remotely-save/remotely-save
